
package com.dynamics.webServices.Warehouse_Activity_Header_WS;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Warehouse_Activity_Header_WS_Port", targetNamespace = "urn:microsoft-dynamics-schemas/page/warehouse_activity_header_ws")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WarehouseActivityHeaderWSPort {


    /**
     * 
     * @param no
     * @param type
     * @return
     *     returns com.dynamics.webServices.Warehouse_Activity_Header_WS.WarehouseActivityHeaderWS
     */
    @WebMethod(operationName = "Read", action = "urn:microsoft-dynamics-schemas/page/warehouse_activity_header_ws:Read")
    @WebResult(name = "Warehouse_Activity_Header_WS", targetNamespace = "urn:microsoft-dynamics-schemas/page/warehouse_activity_header_ws")
    @RequestWrapper(localName = "Read", targetNamespace = "urn:microsoft-dynamics-schemas/page/warehouse_activity_header_ws", className = "com.dynamics.webServices.Warehouse_Activity_Header_WS.Read")
    @ResponseWrapper(localName = "Read_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/warehouse_activity_header_ws", className = "com.dynamics.webServices.Warehouse_Activity_Header_WS.ReadResult")
    public WarehouseActivityHeaderWS read(
        @WebParam(name = "Type", targetNamespace = "urn:microsoft-dynamics-schemas/page/warehouse_activity_header_ws")
        String type,
        @WebParam(name = "No", targetNamespace = "urn:microsoft-dynamics-schemas/page/warehouse_activity_header_ws")
        String no);

    /**
     * 
     * @param recId
     * @return
     *     returns com.dynamics.webServices.Warehouse_Activity_Header_WS.WarehouseActivityHeaderWS
     */
    @WebMethod(operationName = "ReadByRecId", action = "urn:microsoft-dynamics-schemas/page/warehouse_activity_header_ws:ReadByRecId")
    @WebResult(name = "Warehouse_Activity_Header_WS", targetNamespace = "urn:microsoft-dynamics-schemas/page/warehouse_activity_header_ws")
    @RequestWrapper(localName = "ReadByRecId", targetNamespace = "urn:microsoft-dynamics-schemas/page/warehouse_activity_header_ws", className = "com.dynamics.webServices.Warehouse_Activity_Header_WS.ReadByRecId")
    @ResponseWrapper(localName = "ReadByRecId_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/warehouse_activity_header_ws", className = "com.dynamics.webServices.Warehouse_Activity_Header_WS.ReadByRecIdResult")
    public WarehouseActivityHeaderWS readByRecId(
        @WebParam(name = "recId", targetNamespace = "urn:microsoft-dynamics-schemas/page/warehouse_activity_header_ws")
        String recId);

    /**
     * 
     * @param filter
     * @param setSize
     * @param bookmarkKey
     * @return
     *     returns com.dynamics.webServices.Warehouse_Activity_Header_WS.WarehouseActivityHeaderWSList
     */
    @WebMethod(operationName = "ReadMultiple", action = "urn:microsoft-dynamics-schemas/page/warehouse_activity_header_ws:ReadMultiple")
    @WebResult(name = "ReadMultiple_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/warehouse_activity_header_ws")
    @RequestWrapper(localName = "ReadMultiple", targetNamespace = "urn:microsoft-dynamics-schemas/page/warehouse_activity_header_ws", className = "com.dynamics.webServices.Warehouse_Activity_Header_WS.ReadMultiple")
    @ResponseWrapper(localName = "ReadMultiple_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/warehouse_activity_header_ws", className = "com.dynamics.webServices.Warehouse_Activity_Header_WS.ReadMultipleResult")
    public WarehouseActivityHeaderWSList readMultiple(
        @WebParam(name = "filter", targetNamespace = "urn:microsoft-dynamics-schemas/page/warehouse_activity_header_ws")
        List<WarehouseActivityHeaderWSFilter> filter,
        @WebParam(name = "bookmarkKey", targetNamespace = "urn:microsoft-dynamics-schemas/page/warehouse_activity_header_ws")
        String bookmarkKey,
        @WebParam(name = "setSize", targetNamespace = "urn:microsoft-dynamics-schemas/page/warehouse_activity_header_ws")
        int setSize);

    /**
     * 
     * @param key
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "IsUpdated", action = "urn:microsoft-dynamics-schemas/page/warehouse_activity_header_ws:IsUpdated")
    @WebResult(name = "IsUpdated_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/warehouse_activity_header_ws")
    @RequestWrapper(localName = "IsUpdated", targetNamespace = "urn:microsoft-dynamics-schemas/page/warehouse_activity_header_ws", className = "com.dynamics.webServices.Warehouse_Activity_Header_WS.IsUpdated")
    @ResponseWrapper(localName = "IsUpdated_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/warehouse_activity_header_ws", className = "com.dynamics.webServices.Warehouse_Activity_Header_WS.IsUpdatedResult")
    public boolean isUpdated(
        @WebParam(name = "Key", targetNamespace = "urn:microsoft-dynamics-schemas/page/warehouse_activity_header_ws")
        String key);

    /**
     * 
     * @param key
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetRecIdFromKey", action = "urn:microsoft-dynamics-schemas/page/warehouse_activity_header_ws:GetRecIdFromKey")
    @WebResult(name = "GetRecIdFromKey_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/warehouse_activity_header_ws")
    @RequestWrapper(localName = "GetRecIdFromKey", targetNamespace = "urn:microsoft-dynamics-schemas/page/warehouse_activity_header_ws", className = "com.dynamics.webServices.Warehouse_Activity_Header_WS.GetRecIdFromKey")
    @ResponseWrapper(localName = "GetRecIdFromKey_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/warehouse_activity_header_ws", className = "com.dynamics.webServices.Warehouse_Activity_Header_WS.GetRecIdFromKeyResult")
    public String getRecIdFromKey(
        @WebParam(name = "Key", targetNamespace = "urn:microsoft-dynamics-schemas/page/warehouse_activity_header_ws")
        String key);

    /**
     * 
     * @param warehouseActivityHeaderWS
     */
    @WebMethod(operationName = "Create", action = "urn:microsoft-dynamics-schemas/page/warehouse_activity_header_ws:Create")
    @RequestWrapper(localName = "Create", targetNamespace = "urn:microsoft-dynamics-schemas/page/warehouse_activity_header_ws", className = "com.dynamics.webServices.Warehouse_Activity_Header_WS.Create")
    @ResponseWrapper(localName = "Create_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/warehouse_activity_header_ws", className = "com.dynamics.webServices.Warehouse_Activity_Header_WS.CreateResult")
    public void create(
        @WebParam(name = "Warehouse_Activity_Header_WS", targetNamespace = "urn:microsoft-dynamics-schemas/page/warehouse_activity_header_ws", mode = WebParam.Mode.INOUT)
        Holder<WarehouseActivityHeaderWS> warehouseActivityHeaderWS);

    /**
     * 
     * @param warehouseActivityHeaderWSList
     */
    @WebMethod(operationName = "CreateMultiple", action = "urn:microsoft-dynamics-schemas/page/warehouse_activity_header_ws:CreateMultiple")
    @RequestWrapper(localName = "CreateMultiple", targetNamespace = "urn:microsoft-dynamics-schemas/page/warehouse_activity_header_ws", className = "com.dynamics.webServices.Warehouse_Activity_Header_WS.CreateMultiple")
    @ResponseWrapper(localName = "CreateMultiple_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/warehouse_activity_header_ws", className = "com.dynamics.webServices.Warehouse_Activity_Header_WS.CreateMultipleResult")
    public void createMultiple(
        @WebParam(name = "Warehouse_Activity_Header_WS_List", targetNamespace = "urn:microsoft-dynamics-schemas/page/warehouse_activity_header_ws", mode = WebParam.Mode.INOUT)
        Holder<WarehouseActivityHeaderWSList> warehouseActivityHeaderWSList);

    /**
     * 
     * @param warehouseActivityHeaderWS
     */
    @WebMethod(operationName = "Update", action = "urn:microsoft-dynamics-schemas/page/warehouse_activity_header_ws:Update")
    @RequestWrapper(localName = "Update", targetNamespace = "urn:microsoft-dynamics-schemas/page/warehouse_activity_header_ws", className = "com.dynamics.webServices.Warehouse_Activity_Header_WS.Update")
    @ResponseWrapper(localName = "Update_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/warehouse_activity_header_ws", className = "com.dynamics.webServices.Warehouse_Activity_Header_WS.UpdateResult")
    public void update(
        @WebParam(name = "Warehouse_Activity_Header_WS", targetNamespace = "urn:microsoft-dynamics-schemas/page/warehouse_activity_header_ws", mode = WebParam.Mode.INOUT)
        Holder<WarehouseActivityHeaderWS> warehouseActivityHeaderWS);

    /**
     * 
     * @param warehouseActivityHeaderWSList
     */
    @WebMethod(operationName = "UpdateMultiple", action = "urn:microsoft-dynamics-schemas/page/warehouse_activity_header_ws:UpdateMultiple")
    @RequestWrapper(localName = "UpdateMultiple", targetNamespace = "urn:microsoft-dynamics-schemas/page/warehouse_activity_header_ws", className = "com.dynamics.webServices.Warehouse_Activity_Header_WS.UpdateMultiple")
    @ResponseWrapper(localName = "UpdateMultiple_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/warehouse_activity_header_ws", className = "com.dynamics.webServices.Warehouse_Activity_Header_WS.UpdateMultipleResult")
    public void updateMultiple(
        @WebParam(name = "Warehouse_Activity_Header_WS_List", targetNamespace = "urn:microsoft-dynamics-schemas/page/warehouse_activity_header_ws", mode = WebParam.Mode.INOUT)
        Holder<WarehouseActivityHeaderWSList> warehouseActivityHeaderWSList);

    /**
     * 
     * @param key
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "Delete", action = "urn:microsoft-dynamics-schemas/page/warehouse_activity_header_ws:Delete")
    @WebResult(name = "Delete_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/warehouse_activity_header_ws")
    @RequestWrapper(localName = "Delete", targetNamespace = "urn:microsoft-dynamics-schemas/page/warehouse_activity_header_ws", className = "com.dynamics.webServices.Warehouse_Activity_Header_WS.Delete")
    @ResponseWrapper(localName = "Delete_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/warehouse_activity_header_ws", className = "com.dynamics.webServices.Warehouse_Activity_Header_WS.DeleteResult")
    public boolean delete(
        @WebParam(name = "Key", targetNamespace = "urn:microsoft-dynamics-schemas/page/warehouse_activity_header_ws")
        String key);

}
