
package com.dynamics.webServices.Warehouse_Activity_Header_WS;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Warehouse_Activity_Header_WS_Service", targetNamespace = "urn:microsoft-dynamics-schemas/page/warehouse_activity_header_ws", wsdlLocation = "./wsdl//Warehouse_Activity_Header_WS.xml")
public class WarehouseActivityHeaderWSService
    extends Service
{

    private final static URL WAREHOUSEACTIVITYHEADERWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException WAREHOUSEACTIVITYHEADERWSSERVICE_EXCEPTION;
    private final static QName WAREHOUSEACTIVITYHEADERWSSERVICE_QNAME = new QName("urn:microsoft-dynamics-schemas/page/warehouse_activity_header_ws", "Warehouse_Activity_Header_WS_Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/Port\u00e1til1/Desktop/V6/Warehouse_Activity_Header_WS.xml");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WAREHOUSEACTIVITYHEADERWSSERVICE_WSDL_LOCATION = url;
        WAREHOUSEACTIVITYHEADERWSSERVICE_EXCEPTION = e;
    }

    public WarehouseActivityHeaderWSService() {
        super(__getWsdlLocation(), WAREHOUSEACTIVITYHEADERWSSERVICE_QNAME);
    }

    public WarehouseActivityHeaderWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WAREHOUSEACTIVITYHEADERWSSERVICE_QNAME, features);
    }

    public WarehouseActivityHeaderWSService(URL wsdlLocation) {
        super(wsdlLocation, WAREHOUSEACTIVITYHEADERWSSERVICE_QNAME);
    }

    public WarehouseActivityHeaderWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WAREHOUSEACTIVITYHEADERWSSERVICE_QNAME, features);
    }

    public WarehouseActivityHeaderWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WarehouseActivityHeaderWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WarehouseActivityHeaderWSPort
     */
    @WebEndpoint(name = "Warehouse_Activity_Header_WS_Port")
    public WarehouseActivityHeaderWSPort getWarehouseActivityHeaderWSPort() {
        return super.getPort(new QName("urn:microsoft-dynamics-schemas/page/warehouse_activity_header_ws", "Warehouse_Activity_Header_WS_Port"), WarehouseActivityHeaderWSPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WarehouseActivityHeaderWSPort
     */
    @WebEndpoint(name = "Warehouse_Activity_Header_WS_Port")
    public WarehouseActivityHeaderWSPort getWarehouseActivityHeaderWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:microsoft-dynamics-schemas/page/warehouse_activity_header_ws", "Warehouse_Activity_Header_WS_Port"), WarehouseActivityHeaderWSPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WAREHOUSEACTIVITYHEADERWSSERVICE_EXCEPTION!= null) {
            throw WAREHOUSEACTIVITYHEADERWSSERVICE_EXCEPTION;
        }
        return WAREHOUSEACTIVITYHEADERWSSERVICE_WSDL_LOCATION;
    }

}
