
package com.dynamics.webServices.Bin_WS;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Bin_WS_Service", targetNamespace = "urn:microsoft-dynamics-schemas/page/bin_ws", wsdlLocation = "./wsdl//Bin_WS.xml")
public class BinWSService
    extends Service
{

    private final static URL BINWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException BINWSSERVICE_EXCEPTION;
    private final static QName BINWSSERVICE_QNAME = new QName("urn:microsoft-dynamics-schemas/page/bin_ws", "Bin_WS_Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("./wsdl//Bin_WS.xml");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BINWSSERVICE_WSDL_LOCATION = url;
        BINWSSERVICE_EXCEPTION = e;
    }

    public BinWSService() {
        super(__getWsdlLocation(), BINWSSERVICE_QNAME);
    }

    public BinWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BINWSSERVICE_QNAME, features);
    }

    public BinWSService(URL wsdlLocation) {
        super(wsdlLocation, BINWSSERVICE_QNAME);
    }

    public BinWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BINWSSERVICE_QNAME, features);
    }

    public BinWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BinWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BinWSPort
     */
    @WebEndpoint(name = "Bin_WS_Port")
    public BinWSPort getBinWSPort() {
        return super.getPort(new QName("urn:microsoft-dynamics-schemas/page/bin_ws", "Bin_WS_Port"), BinWSPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BinWSPort
     */
    @WebEndpoint(name = "Bin_WS_Port")
    public BinWSPort getBinWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:microsoft-dynamics-schemas/page/bin_ws", "Bin_WS_Port"), BinWSPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BINWSSERVICE_EXCEPTION!= null) {
            throw BINWSSERVICE_EXCEPTION;
        }
        return BINWSSERVICE_WSDL_LOCATION;
    }

}
