
package com.dynamics.webServices.Prod_Order_Component_WS;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Prod_Order_Component_WS_Service", targetNamespace = "urn:microsoft-dynamics-schemas/page/prod_order_component_ws", wsdlLocation = "./wsdl//Prod_Order_Component_WS.xml")
public class ProdOrderComponentWSService
    extends Service
{

    private final static URL PRODORDERCOMPONENTWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException PRODORDERCOMPONENTWSSERVICE_EXCEPTION;
    private final static QName PRODORDERCOMPONENTWSSERVICE_QNAME = new QName("urn:microsoft-dynamics-schemas/page/prod_order_component_ws", "Prod_Order_Component_WS_Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("./wsdl//Prod_Order_Component_WS.xml");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRODORDERCOMPONENTWSSERVICE_WSDL_LOCATION = url;
        PRODORDERCOMPONENTWSSERVICE_EXCEPTION = e;
    }

    public ProdOrderComponentWSService() {
        super(__getWsdlLocation(), PRODORDERCOMPONENTWSSERVICE_QNAME);
    }

    public ProdOrderComponentWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRODORDERCOMPONENTWSSERVICE_QNAME, features);
    }

    public ProdOrderComponentWSService(URL wsdlLocation) {
        super(wsdlLocation, PRODORDERCOMPONENTWSSERVICE_QNAME);
    }

    public ProdOrderComponentWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRODORDERCOMPONENTWSSERVICE_QNAME, features);
    }

    public ProdOrderComponentWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProdOrderComponentWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProdOrderComponentWSPort
     */
    @WebEndpoint(name = "Prod_Order_Component_WS_Port")
    public ProdOrderComponentWSPort getProdOrderComponentWSPort() {
        return super.getPort(new QName("urn:microsoft-dynamics-schemas/page/prod_order_component_ws", "Prod_Order_Component_WS_Port"), ProdOrderComponentWSPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProdOrderComponentWSPort
     */
    @WebEndpoint(name = "Prod_Order_Component_WS_Port")
    public ProdOrderComponentWSPort getProdOrderComponentWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:microsoft-dynamics-schemas/page/prod_order_component_ws", "Prod_Order_Component_WS_Port"), ProdOrderComponentWSPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRODORDERCOMPONENTWSSERVICE_EXCEPTION!= null) {
            throw PRODORDERCOMPONENTWSSERVICE_EXCEPTION;
        }
        return PRODORDERCOMPONENTWSSERVICE_WSDL_LOCATION;
    }

}
