
package com.dynamics.webServices.Prod_Order_Component_WS;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Prod_Order_Component_WS_Port", targetNamespace = "urn:microsoft-dynamics-schemas/page/prod_order_component_ws")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProdOrderComponentWSPort {


    /**
     * 
     * @param prodOrderNo
     * @param prodOrderLineNo
     * @param status
     * @return
     *     returns com.dynamics.webServices.Prod_Order_Component_WS.ProdOrderComponentWS
     */
    @WebMethod(operationName = "Read", action = "urn:microsoft-dynamics-schemas/page/prod_order_component_ws:Read")
    @WebResult(name = "Prod_Order_Component_WS", targetNamespace = "urn:microsoft-dynamics-schemas/page/prod_order_component_ws")
    @RequestWrapper(localName = "Read", targetNamespace = "urn:microsoft-dynamics-schemas/page/prod_order_component_ws", className = "com.dynamics.webServices.Prod_Order_Component_WS.Read")
    @ResponseWrapper(localName = "Read_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/prod_order_component_ws", className = "com.dynamics.webServices.Prod_Order_Component_WS.ReadResult")
    public ProdOrderComponentWS read(
        @WebParam(name = "Status", targetNamespace = "urn:microsoft-dynamics-schemas/page/prod_order_component_ws")
        String status,
        @WebParam(name = "Prod_Order_No", targetNamespace = "urn:microsoft-dynamics-schemas/page/prod_order_component_ws")
        String prodOrderNo,
        @WebParam(name = "Prod_Order_Line_No", targetNamespace = "urn:microsoft-dynamics-schemas/page/prod_order_component_ws")
        int prodOrderLineNo);

    /**
     * 
     * @param recId
     * @return
     *     returns com.dynamics.webServices.Prod_Order_Component_WS.ProdOrderComponentWS
     */
    @WebMethod(operationName = "ReadByRecId", action = "urn:microsoft-dynamics-schemas/page/prod_order_component_ws:ReadByRecId")
    @WebResult(name = "Prod_Order_Component_WS", targetNamespace = "urn:microsoft-dynamics-schemas/page/prod_order_component_ws")
    @RequestWrapper(localName = "ReadByRecId", targetNamespace = "urn:microsoft-dynamics-schemas/page/prod_order_component_ws", className = "com.dynamics.webServices.Prod_Order_Component_WS.ReadByRecId")
    @ResponseWrapper(localName = "ReadByRecId_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/prod_order_component_ws", className = "com.dynamics.webServices.Prod_Order_Component_WS.ReadByRecIdResult")
    public ProdOrderComponentWS readByRecId(
        @WebParam(name = "recId", targetNamespace = "urn:microsoft-dynamics-schemas/page/prod_order_component_ws")
        String recId);

    /**
     * 
     * @param filter
     * @param setSize
     * @param bookmarkKey
     * @return
     *     returns com.dynamics.webServices.Prod_Order_Component_WS.ProdOrderComponentWSList
     */
    @WebMethod(operationName = "ReadMultiple", action = "urn:microsoft-dynamics-schemas/page/prod_order_component_ws:ReadMultiple")
    @WebResult(name = "ReadMultiple_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/prod_order_component_ws")
    @RequestWrapper(localName = "ReadMultiple", targetNamespace = "urn:microsoft-dynamics-schemas/page/prod_order_component_ws", className = "com.dynamics.webServices.Prod_Order_Component_WS.ReadMultiple")
    @ResponseWrapper(localName = "ReadMultiple_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/prod_order_component_ws", className = "com.dynamics.webServices.Prod_Order_Component_WS.ReadMultipleResult")
    public ProdOrderComponentWSList readMultiple(
        @WebParam(name = "filter", targetNamespace = "urn:microsoft-dynamics-schemas/page/prod_order_component_ws")
        List<ProdOrderComponentWSFilter> filter,
        @WebParam(name = "bookmarkKey", targetNamespace = "urn:microsoft-dynamics-schemas/page/prod_order_component_ws")
        String bookmarkKey,
        @WebParam(name = "setSize", targetNamespace = "urn:microsoft-dynamics-schemas/page/prod_order_component_ws")
        int setSize);

    /**
     * 
     * @param key
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "IsUpdated", action = "urn:microsoft-dynamics-schemas/page/prod_order_component_ws:IsUpdated")
    @WebResult(name = "IsUpdated_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/prod_order_component_ws")
    @RequestWrapper(localName = "IsUpdated", targetNamespace = "urn:microsoft-dynamics-schemas/page/prod_order_component_ws", className = "com.dynamics.webServices.Prod_Order_Component_WS.IsUpdated")
    @ResponseWrapper(localName = "IsUpdated_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/prod_order_component_ws", className = "com.dynamics.webServices.Prod_Order_Component_WS.IsUpdatedResult")
    public boolean isUpdated(
        @WebParam(name = "Key", targetNamespace = "urn:microsoft-dynamics-schemas/page/prod_order_component_ws")
        String key);

    /**
     * 
     * @param key
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetRecIdFromKey", action = "urn:microsoft-dynamics-schemas/page/prod_order_component_ws:GetRecIdFromKey")
    @WebResult(name = "GetRecIdFromKey_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/prod_order_component_ws")
    @RequestWrapper(localName = "GetRecIdFromKey", targetNamespace = "urn:microsoft-dynamics-schemas/page/prod_order_component_ws", className = "com.dynamics.webServices.Prod_Order_Component_WS.GetRecIdFromKey")
    @ResponseWrapper(localName = "GetRecIdFromKey_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/prod_order_component_ws", className = "com.dynamics.webServices.Prod_Order_Component_WS.GetRecIdFromKeyResult")
    public String getRecIdFromKey(
        @WebParam(name = "Key", targetNamespace = "urn:microsoft-dynamics-schemas/page/prod_order_component_ws")
        String key);

}
