
package com.dynamics.webServices.Bin_Content_WS;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Bin_Content_WS_Service", targetNamespace = "urn:microsoft-dynamics-schemas/page/bin_content_ws", wsdlLocation = "./wsdl//Bin_Content_WS.xml")
public class BinContentWSService
    extends Service
{

    private final static URL BINCONTENTWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException BINCONTENTWSSERVICE_EXCEPTION;
    private final static QName BINCONTENTWSSERVICE_QNAME = new QName("urn:microsoft-dynamics-schemas/page/bin_content_ws", "Bin_Content_WS_Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("./wsdl//Bin_Content_WS.xml");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BINCONTENTWSSERVICE_WSDL_LOCATION = url;
        BINCONTENTWSSERVICE_EXCEPTION = e;
    }

    public BinContentWSService() {
        super(__getWsdlLocation(), BINCONTENTWSSERVICE_QNAME);
    }

    public BinContentWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BINCONTENTWSSERVICE_QNAME, features);
    }

    public BinContentWSService(URL wsdlLocation) {
        super(wsdlLocation, BINCONTENTWSSERVICE_QNAME);
    }

    public BinContentWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BINCONTENTWSSERVICE_QNAME, features);
    }

    public BinContentWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BinContentWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BinContentWSPort
     */
    @WebEndpoint(name = "Bin_Content_WS_Port")
    public BinContentWSPort getBinContentWSPort() {
        return super.getPort(new QName("urn:microsoft-dynamics-schemas/page/bin_content_ws", "Bin_Content_WS_Port"), BinContentWSPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BinContentWSPort
     */
    @WebEndpoint(name = "Bin_Content_WS_Port")
    public BinContentWSPort getBinContentWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:microsoft-dynamics-schemas/page/bin_content_ws", "Bin_Content_WS_Port"), BinContentWSPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BINCONTENTWSSERVICE_EXCEPTION!= null) {
            throw BINCONTENTWSSERVICE_EXCEPTION;
        }
        return BINCONTENTWSSERVICE_WSDL_LOCATION;
    }

}
