
package com.dynamics.webServices.Item_Card;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Item_Card_Port", targetNamespace = "urn:microsoft-dynamics-schemas/page/item_card")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ItemCardPort {


    /**
     * 
     * @param no
     * @return
     *     returns Item_Card.ItemCard
     */
    @WebMethod(operationName = "Read", action = "urn:microsoft-dynamics-schemas/page/item_card:Read")
    @WebResult(name = "Item_Card", targetNamespace = "urn:microsoft-dynamics-schemas/page/item_card")
    @RequestWrapper(localName = "Read", targetNamespace = "urn:microsoft-dynamics-schemas/page/item_card", className = "Item_Card.Read")
    @ResponseWrapper(localName = "Read_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/item_card", className = "Item_Card.ReadResult")
    public ItemCard read(
        @WebParam(name = "No", targetNamespace = "urn:microsoft-dynamics-schemas/page/item_card")
        String no);

    /**
     * 
     * @param recId
     * @return
     *     returns Item_Card.ItemCard
     */
    @WebMethod(operationName = "ReadByRecId", action = "urn:microsoft-dynamics-schemas/page/item_card:ReadByRecId")
    @WebResult(name = "Item_Card", targetNamespace = "urn:microsoft-dynamics-schemas/page/item_card")
    @RequestWrapper(localName = "ReadByRecId", targetNamespace = "urn:microsoft-dynamics-schemas/page/item_card", className = "Item_Card.ReadByRecId")
    @ResponseWrapper(localName = "ReadByRecId_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/item_card", className = "Item_Card.ReadByRecIdResult")
    public ItemCard readByRecId(
        @WebParam(name = "recId", targetNamespace = "urn:microsoft-dynamics-schemas/page/item_card")
        String recId);

    /**
     * 
     * @param filter
     * @param setSize
     * @param bookmarkKey
     * @return
     *     returns Item_Card.ItemCardList
     */
    @WebMethod(operationName = "ReadMultiple", action = "urn:microsoft-dynamics-schemas/page/item_card:ReadMultiple")
    @WebResult(name = "ReadMultiple_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/item_card")
    @RequestWrapper(localName = "ReadMultiple", targetNamespace = "urn:microsoft-dynamics-schemas/page/item_card", className = "Item_Card.ReadMultiple")
    @ResponseWrapper(localName = "ReadMultiple_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/item_card", className = "Item_Card.ReadMultipleResult")
    public ItemCardList readMultiple(
        @WebParam(name = "filter", targetNamespace = "urn:microsoft-dynamics-schemas/page/item_card")
        List<ItemCardFilter> filter,
        @WebParam(name = "bookmarkKey", targetNamespace = "urn:microsoft-dynamics-schemas/page/item_card")
        String bookmarkKey,
        @WebParam(name = "setSize", targetNamespace = "urn:microsoft-dynamics-schemas/page/item_card")
        int setSize);

    /**
     * 
     * @param key
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "IsUpdated", action = "urn:microsoft-dynamics-schemas/page/item_card:IsUpdated")
    @WebResult(name = "IsUpdated_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/item_card")
    @RequestWrapper(localName = "IsUpdated", targetNamespace = "urn:microsoft-dynamics-schemas/page/item_card", className = "Item_Card.IsUpdated")
    @ResponseWrapper(localName = "IsUpdated_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/item_card", className = "Item_Card.IsUpdatedResult")
    public boolean isUpdated(
        @WebParam(name = "Key", targetNamespace = "urn:microsoft-dynamics-schemas/page/item_card")
        String key);

    /**
     * 
     * @param key
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetRecIdFromKey", action = "urn:microsoft-dynamics-schemas/page/item_card:GetRecIdFromKey")
    @WebResult(name = "GetRecIdFromKey_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/item_card")
    @RequestWrapper(localName = "GetRecIdFromKey", targetNamespace = "urn:microsoft-dynamics-schemas/page/item_card", className = "Item_Card.GetRecIdFromKey")
    @ResponseWrapper(localName = "GetRecIdFromKey_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/item_card", className = "Item_Card.GetRecIdFromKeyResult")
    public String getRecIdFromKey(
        @WebParam(name = "Key", targetNamespace = "urn:microsoft-dynamics-schemas/page/item_card")
        String key);

    /**
     * 
     * @param itemCard
     */
    @WebMethod(operationName = "Create", action = "urn:microsoft-dynamics-schemas/page/item_card:Create")
    @RequestWrapper(localName = "Create", targetNamespace = "urn:microsoft-dynamics-schemas/page/item_card", className = "Item_Card.Create")
    @ResponseWrapper(localName = "Create_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/item_card", className = "Item_Card.CreateResult")
    public void create(
        @WebParam(name = "Item_Card", targetNamespace = "urn:microsoft-dynamics-schemas/page/item_card", mode = WebParam.Mode.INOUT)
        Holder<ItemCard> itemCard);

    /**
     * 
     * @param itemCardList
     */
    @WebMethod(operationName = "CreateMultiple", action = "urn:microsoft-dynamics-schemas/page/item_card:CreateMultiple")
    @RequestWrapper(localName = "CreateMultiple", targetNamespace = "urn:microsoft-dynamics-schemas/page/item_card", className = "Item_Card.CreateMultiple")
    @ResponseWrapper(localName = "CreateMultiple_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/item_card", className = "Item_Card.CreateMultipleResult")
    public void createMultiple(
        @WebParam(name = "Item_Card_List", targetNamespace = "urn:microsoft-dynamics-schemas/page/item_card", mode = WebParam.Mode.INOUT)
        Holder<ItemCardList> itemCardList);

    /**
     * 
     * @param itemCard
     */
    @WebMethod(operationName = "Update", action = "urn:microsoft-dynamics-schemas/page/item_card:Update")
    @RequestWrapper(localName = "Update", targetNamespace = "urn:microsoft-dynamics-schemas/page/item_card", className = "Item_Card.Update")
    @ResponseWrapper(localName = "Update_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/item_card", className = "Item_Card.UpdateResult")
    public void update(
        @WebParam(name = "Item_Card", targetNamespace = "urn:microsoft-dynamics-schemas/page/item_card", mode = WebParam.Mode.INOUT)
        Holder<ItemCard> itemCard);

    /**
     * 
     * @param itemCardList
     */
    @WebMethod(operationName = "UpdateMultiple", action = "urn:microsoft-dynamics-schemas/page/item_card:UpdateMultiple")
    @RequestWrapper(localName = "UpdateMultiple", targetNamespace = "urn:microsoft-dynamics-schemas/page/item_card", className = "Item_Card.UpdateMultiple")
    @ResponseWrapper(localName = "UpdateMultiple_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/item_card", className = "Item_Card.UpdateMultipleResult")
    public void updateMultiple(
        @WebParam(name = "Item_Card_List", targetNamespace = "urn:microsoft-dynamics-schemas/page/item_card", mode = WebParam.Mode.INOUT)
        Holder<ItemCardList> itemCardList);

    /**
     * 
     * @param key
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "Delete", action = "urn:microsoft-dynamics-schemas/page/item_card:Delete")
    @WebResult(name = "Delete_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/item_card")
    @RequestWrapper(localName = "Delete", targetNamespace = "urn:microsoft-dynamics-schemas/page/item_card", className = "Item_Card.Delete")
    @ResponseWrapper(localName = "Delete_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/item_card", className = "Item_Card.DeleteResult")
    public boolean delete(
        @WebParam(name = "Key", targetNamespace = "urn:microsoft-dynamics-schemas/page/item_card")
        String key);

}
