
package com.dynamics.webServices.Item_Card;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Item_Card_Service", targetNamespace = "urn:microsoft-dynamics-schemas/page/item_card", wsdlLocation = "file:/C:/Users/Port\u00e1til/Desktop/Item_Card.xml")
public class ItemCardService
    extends Service
{

    private final static URL ITEMCARDSERVICE_WSDL_LOCATION;
    private final static WebServiceException ITEMCARDSERVICE_EXCEPTION;
    private final static QName ITEMCARDSERVICE_QNAME = new QName("urn:microsoft-dynamics-schemas/page/item_card", "Item_Card_Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/Port\u00e1til/Desktop/Item_Card.xml");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ITEMCARDSERVICE_WSDL_LOCATION = url;
        ITEMCARDSERVICE_EXCEPTION = e;
    }

    public ItemCardService() {
        super(__getWsdlLocation(), ITEMCARDSERVICE_QNAME);
    }

    public ItemCardService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ITEMCARDSERVICE_QNAME, features);
    }

    public ItemCardService(URL wsdlLocation) {
        super(wsdlLocation, ITEMCARDSERVICE_QNAME);
    }

    public ItemCardService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ITEMCARDSERVICE_QNAME, features);
    }

    public ItemCardService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ItemCardService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ItemCardPort
     */
    @WebEndpoint(name = "Item_Card_Port")
    public ItemCardPort getItemCardPort() {
        return super.getPort(new QName("urn:microsoft-dynamics-schemas/page/item_card", "Item_Card_Port"), ItemCardPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ItemCardPort
     */
    @WebEndpoint(name = "Item_Card_Port")
    public ItemCardPort getItemCardPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:microsoft-dynamics-schemas/page/item_card", "Item_Card_Port"), ItemCardPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ITEMCARDSERVICE_EXCEPTION!= null) {
            throw ITEMCARDSERVICE_EXCEPTION;
        }
        return ITEMCARDSERVICE_WSDL_LOCATION;
    }

}
