
package com.dynamics.webServices.Item_Card_WS;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Item_Card_WS_Service", targetNamespace = "urn:microsoft-dynamics-schemas/page/item_card_ws", wsdlLocation = "./wsdl//Item_Card_WS.xml")
public class ItemCardWSService
    extends Service
{

    private final static URL ITEMCARDWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException ITEMCARDWSSERVICE_EXCEPTION;
    private final static QName ITEMCARDWSSERVICE_QNAME = new QName("urn:microsoft-dynamics-schemas/page/item_card_ws", "Item_Card_WS_Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("./wsdl//Item_Card_WS.xml");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ITEMCARDWSSERVICE_WSDL_LOCATION = url;
        ITEMCARDWSSERVICE_EXCEPTION = e;
    }

    public ItemCardWSService() {
        super(__getWsdlLocation(), ITEMCARDWSSERVICE_QNAME);
    }

    public ItemCardWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ITEMCARDWSSERVICE_QNAME, features);
    }

    public ItemCardWSService(URL wsdlLocation) {
        super(wsdlLocation, ITEMCARDWSSERVICE_QNAME);
    }

    public ItemCardWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ITEMCARDWSSERVICE_QNAME, features);
    }

    public ItemCardWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ItemCardWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ItemCardWSPort
     */
    @WebEndpoint(name = "Item_Card_WS_Port")
    public ItemCardWSPort getItemCardWSPort() {
        return super.getPort(new QName("urn:microsoft-dynamics-schemas/page/item_card_ws", "Item_Card_WS_Port"), ItemCardWSPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ItemCardWSPort
     */
    @WebEndpoint(name = "Item_Card_WS_Port")
    public ItemCardWSPort getItemCardWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:microsoft-dynamics-schemas/page/item_card_ws", "Item_Card_WS_Port"), ItemCardWSPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ITEMCARDWSSERVICE_EXCEPTION!= null) {
            throw ITEMCARDWSSERVICE_EXCEPTION;
        }
        return ITEMCARDWSSERVICE_WSDL_LOCATION;
    }

}
