
package com.dynamics.webServices.Warehouse_Receipt_Line_WS;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Warehouse_Receipt_Line_WS_Service", targetNamespace = "urn:microsoft-dynamics-schemas/page/warehouse_receipt_line_ws", wsdlLocation = "./wsdl//Warehouse_Receipt_Line_WS.xml")
public class WarehouseReceiptLineWSService
    extends Service
{

    private final static URL WAREHOUSERECEIPTLINEWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException WAREHOUSERECEIPTLINEWSSERVICE_EXCEPTION;
    private final static QName WAREHOUSERECEIPTLINEWSSERVICE_QNAME = new QName("urn:microsoft-dynamics-schemas/page/warehouse_receipt_line_ws", "Warehouse_Receipt_Line_WS_Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("./wsdl//Warehouse_Receipt_Line_WS.xml");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WAREHOUSERECEIPTLINEWSSERVICE_WSDL_LOCATION = url;
        WAREHOUSERECEIPTLINEWSSERVICE_EXCEPTION = e;
    }

    public WarehouseReceiptLineWSService() {
        super(__getWsdlLocation(), WAREHOUSERECEIPTLINEWSSERVICE_QNAME);
    }

    public WarehouseReceiptLineWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WAREHOUSERECEIPTLINEWSSERVICE_QNAME, features);
    }

    public WarehouseReceiptLineWSService(URL wsdlLocation) {
        super(wsdlLocation, WAREHOUSERECEIPTLINEWSSERVICE_QNAME);
    }

    public WarehouseReceiptLineWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WAREHOUSERECEIPTLINEWSSERVICE_QNAME, features);
    }

    public WarehouseReceiptLineWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WarehouseReceiptLineWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WarehouseReceiptLineWSPort
     */
    @WebEndpoint(name = "Warehouse_Receipt_Line_WS_Port")
    public WarehouseReceiptLineWSPort getWarehouseReceiptLineWSPort() {
        return super.getPort(new QName("urn:microsoft-dynamics-schemas/page/warehouse_receipt_line_ws", "Warehouse_Receipt_Line_WS_Port"), WarehouseReceiptLineWSPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WarehouseReceiptLineWSPort
     */
    @WebEndpoint(name = "Warehouse_Receipt_Line_WS_Port")
    public WarehouseReceiptLineWSPort getWarehouseReceiptLineWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:microsoft-dynamics-schemas/page/warehouse_receipt_line_ws", "Warehouse_Receipt_Line_WS_Port"), WarehouseReceiptLineWSPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WAREHOUSERECEIPTLINEWSSERVICE_EXCEPTION!= null) {
            throw WAREHOUSERECEIPTLINEWSSERVICE_EXCEPTION;
        }
        return WAREHOUSERECEIPTLINEWSSERVICE_WSDL_LOCATION;
    }

}
