
package com.dynamics.webServices.RF_Functions;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RF_Functions", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/RF_Functions", wsdlLocation = "./wsdl//RF_Functions.xml")
public class RFFunctions
    extends Service
{

    private final static URL RFFUNCTIONS_WSDL_LOCATION;
    private final static WebServiceException RFFUNCTIONS_EXCEPTION;
    private final static QName RFFUNCTIONS_QNAME = new QName("urn:microsoft-dynamics-schemas/codeunit/RF_Functions", "RF_Functions");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("./wsdl//RF_Functions.xml");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RFFUNCTIONS_WSDL_LOCATION = url;
        RFFUNCTIONS_EXCEPTION = e;
    }

    public RFFunctions() {
        super(__getWsdlLocation(), RFFUNCTIONS_QNAME);
    }

    public RFFunctions(WebServiceFeature... features) {
        super(__getWsdlLocation(), RFFUNCTIONS_QNAME, features);
    }

    public RFFunctions(URL wsdlLocation) {
        super(wsdlLocation, RFFUNCTIONS_QNAME);
    }

    public RFFunctions(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RFFUNCTIONS_QNAME, features);
    }

    public RFFunctions(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RFFunctions(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RFFunctionsPort
     */
    @WebEndpoint(name = "RF_Functions_Port")
    public RFFunctionsPort getRFFunctionsPort() {
        return super.getPort(new QName("urn:microsoft-dynamics-schemas/codeunit/RF_Functions", "RF_Functions_Port"), RFFunctionsPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RFFunctionsPort
     */
    @WebEndpoint(name = "RF_Functions_Port")
    public RFFunctionsPort getRFFunctionsPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:microsoft-dynamics-schemas/codeunit/RF_Functions", "RF_Functions_Port"), RFFunctionsPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RFFUNCTIONS_EXCEPTION!= null) {
            throw RFFUNCTIONS_EXCEPTION;
        }
        return RFFUNCTIONS_WSDL_LOCATION;
    }

}
