
package com.dynamics.webServices.Prod_Order_Line_WS;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Prod_Order_Line_WS_Service", targetNamespace = "urn:microsoft-dynamics-schemas/page/prod_order_line_ws", wsdlLocation = "./wsdl//Prod_Order_Line_WS.xml")
public class ProdOrderLineWSService
    extends Service
{

    private final static URL PRODORDERLINEWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException PRODORDERLINEWSSERVICE_EXCEPTION;
    private final static QName PRODORDERLINEWSSERVICE_QNAME = new QName("urn:microsoft-dynamics-schemas/page/prod_order_line_ws", "Prod_Order_Line_WS_Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("./wsdl//Prod_Order_Line_WS.xml");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRODORDERLINEWSSERVICE_WSDL_LOCATION = url;
        PRODORDERLINEWSSERVICE_EXCEPTION = e;
    }

    public ProdOrderLineWSService() {
        super(__getWsdlLocation(), PRODORDERLINEWSSERVICE_QNAME);
    }

    public ProdOrderLineWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRODORDERLINEWSSERVICE_QNAME, features);
    }

    public ProdOrderLineWSService(URL wsdlLocation) {
        super(wsdlLocation, PRODORDERLINEWSSERVICE_QNAME);
    }

    public ProdOrderLineWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRODORDERLINEWSSERVICE_QNAME, features);
    }

    public ProdOrderLineWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProdOrderLineWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProdOrderLineWSPort
     */
    @WebEndpoint(name = "Prod_Order_Line_WS_Port")
    public ProdOrderLineWSPort getProdOrderLineWSPort() {
        return super.getPort(new QName("urn:microsoft-dynamics-schemas/page/prod_order_line_ws", "Prod_Order_Line_WS_Port"), ProdOrderLineWSPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProdOrderLineWSPort
     */
    @WebEndpoint(name = "Prod_Order_Line_WS_Port")
    public ProdOrderLineWSPort getProdOrderLineWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:microsoft-dynamics-schemas/page/prod_order_line_ws", "Prod_Order_Line_WS_Port"), ProdOrderLineWSPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRODORDERLINEWSSERVICE_EXCEPTION!= null) {
            throw PRODORDERLINEWSSERVICE_EXCEPTION;
        }
        return PRODORDERLINEWSSERVICE_WSDL_LOCATION;
    }

}
