
package com.dynamics.webServices.Warehouse_Shipment_Line_WS;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Warehouse_Shipment_Line_WS_Service", targetNamespace = "urn:microsoft-dynamics-schemas/page/warehouse_shipment_line_ws", wsdlLocation = "./wsdl/Warehouse_Shipment_Line_WS.xml")
public class WarehouseShipmentLineWSService
    extends Service
{

    private final static URL WAREHOUSESHIPMENTLINEWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException WAREHOUSESHIPMENTLINEWSSERVICE_EXCEPTION;
    private final static QName WAREHOUSESHIPMENTLINEWSSERVICE_QNAME = new QName("urn:microsoft-dynamics-schemas/page/warehouse_shipment_line_ws", "Warehouse_Shipment_Line_WS_Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("./wsdl/Warehouse_Shipment_Line_WS.xml");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WAREHOUSESHIPMENTLINEWSSERVICE_WSDL_LOCATION = url;
        WAREHOUSESHIPMENTLINEWSSERVICE_EXCEPTION = e;
    }

    public WarehouseShipmentLineWSService() {
        super(__getWsdlLocation(), WAREHOUSESHIPMENTLINEWSSERVICE_QNAME);
    }

    public WarehouseShipmentLineWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WAREHOUSESHIPMENTLINEWSSERVICE_QNAME, features);
    }

    public WarehouseShipmentLineWSService(URL wsdlLocation) {
        super(wsdlLocation, WAREHOUSESHIPMENTLINEWSSERVICE_QNAME);
    }

    public WarehouseShipmentLineWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WAREHOUSESHIPMENTLINEWSSERVICE_QNAME, features);
    }

    public WarehouseShipmentLineWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WarehouseShipmentLineWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WarehouseShipmentLineWSPort
     */
    @WebEndpoint(name = "Warehouse_Shipment_Line_WS_Port")
    public WarehouseShipmentLineWSPort getWarehouseShipmentLineWSPort() {
        return super.getPort(new QName("urn:microsoft-dynamics-schemas/page/warehouse_shipment_line_ws", "Warehouse_Shipment_Line_WS_Port"), WarehouseShipmentLineWSPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WarehouseShipmentLineWSPort
     */
    @WebEndpoint(name = "Warehouse_Shipment_Line_WS_Port")
    public WarehouseShipmentLineWSPort getWarehouseShipmentLineWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:microsoft-dynamics-schemas/page/warehouse_shipment_line_ws", "Warehouse_Shipment_Line_WS_Port"), WarehouseShipmentLineWSPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WAREHOUSESHIPMENTLINEWSSERVICE_EXCEPTION!= null) {
            throw WAREHOUSESHIPMENTLINEWSSERVICE_EXCEPTION;
        }
        return WAREHOUSESHIPMENTLINEWSSERVICE_WSDL_LOCATION;
    }

}
