
package com.dynamics.webServices.WS_Whse_Worksheet_Line;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WS_Whse_Worksheet_Line_Service", targetNamespace = "urn:microsoft-dynamics-schemas/page/ws_whse_worksheet_line", wsdlLocation = "file:/C:/Users/Port\u00e1til1/AppData/Local/Temp/tempdir5673997163850978785.tmp/WS_Whse_Worksheet_Line_1.wsdl")
public class WSWhseWorksheetLineService
    extends Service
{

    private final static URL WSWHSEWORKSHEETLINESERVICE_WSDL_LOCATION;
    private final static WebServiceException WSWHSEWORKSHEETLINESERVICE_EXCEPTION;
    private final static QName WSWHSEWORKSHEETLINESERVICE_QNAME = new QName("urn:microsoft-dynamics-schemas/page/ws_whse_worksheet_line", "WS_Whse_Worksheet_Line_Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/Port\u00e1til1/AppData/Local/Temp/tempdir5673997163850978785.tmp/WS_Whse_Worksheet_Line_1.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSWHSEWORKSHEETLINESERVICE_WSDL_LOCATION = url;
        WSWHSEWORKSHEETLINESERVICE_EXCEPTION = e;
    }

    public WSWhseWorksheetLineService() {
        super(__getWsdlLocation(), WSWHSEWORKSHEETLINESERVICE_QNAME);
    }

    public WSWhseWorksheetLineService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSWHSEWORKSHEETLINESERVICE_QNAME, features);
    }

    public WSWhseWorksheetLineService(URL wsdlLocation) {
        super(wsdlLocation, WSWHSEWORKSHEETLINESERVICE_QNAME);
    }

    public WSWhseWorksheetLineService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSWHSEWORKSHEETLINESERVICE_QNAME, features);
    }

    public WSWhseWorksheetLineService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSWhseWorksheetLineService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSWhseWorksheetLinePort
     */
    @WebEndpoint(name = "WS_Whse_Worksheet_Line_Port")
    public WSWhseWorksheetLinePort getWSWhseWorksheetLinePort() {
        return super.getPort(new QName("urn:microsoft-dynamics-schemas/page/ws_whse_worksheet_line", "WS_Whse_Worksheet_Line_Port"), WSWhseWorksheetLinePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSWhseWorksheetLinePort
     */
    @WebEndpoint(name = "WS_Whse_Worksheet_Line_Port")
    public WSWhseWorksheetLinePort getWSWhseWorksheetLinePort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:microsoft-dynamics-schemas/page/ws_whse_worksheet_line", "WS_Whse_Worksheet_Line_Port"), WSWhseWorksheetLinePort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSWHSEWORKSHEETLINESERVICE_EXCEPTION!= null) {
            throw WSWHSEWORKSHEETLINESERVICE_EXCEPTION;
        }
        return WSWHSEWORKSHEETLINESERVICE_WSDL_LOCATION;
    }

}
