
package com.dynamics.webServices.Warehouse_Activity_Line_WS;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Warehouse_Activity_Line_WS_Service", targetNamespace = "urn:microsoft-dynamics-schemas/page/warehouse_activity_line_ws", wsdlLocation = "./wsdl//Warehouse_Activity_Line_WS.xml")
public class WarehouseActivityLineWSService
    extends Service
{

    private final static URL WAREHOUSEACTIVITYLINEWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException WAREHOUSEACTIVITYLINEWSSERVICE_EXCEPTION;
    private final static QName WAREHOUSEACTIVITYLINEWSSERVICE_QNAME = new QName("urn:microsoft-dynamics-schemas/page/warehouse_activity_line_ws", "Warehouse_Activity_Line_WS_Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("./wsdl//Warehouse_Activity_Line_WS.xml");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WAREHOUSEACTIVITYLINEWSSERVICE_WSDL_LOCATION = url;
        WAREHOUSEACTIVITYLINEWSSERVICE_EXCEPTION = e;
    }

    public WarehouseActivityLineWSService() {
        super(__getWsdlLocation(), WAREHOUSEACTIVITYLINEWSSERVICE_QNAME);
    }

    public WarehouseActivityLineWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WAREHOUSEACTIVITYLINEWSSERVICE_QNAME, features);
    }

    public WarehouseActivityLineWSService(URL wsdlLocation) {
        super(wsdlLocation, WAREHOUSEACTIVITYLINEWSSERVICE_QNAME);
    }

    public WarehouseActivityLineWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WAREHOUSEACTIVITYLINEWSSERVICE_QNAME, features);
    }

    public WarehouseActivityLineWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WarehouseActivityLineWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WarehouseActivityLineWSPort
     */
    @WebEndpoint(name = "Warehouse_Activity_Line_WS_Port")
    public WarehouseActivityLineWSPort getWarehouseActivityLineWSPort() {
        return super.getPort(new QName("urn:microsoft-dynamics-schemas/page/warehouse_activity_line_ws", "Warehouse_Activity_Line_WS_Port"), WarehouseActivityLineWSPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WarehouseActivityLineWSPort
     */
    @WebEndpoint(name = "Warehouse_Activity_Line_WS_Port")
    public WarehouseActivityLineWSPort getWarehouseActivityLineWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:microsoft-dynamics-schemas/page/warehouse_activity_line_ws", "Warehouse_Activity_Line_WS_Port"), WarehouseActivityLineWSPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WAREHOUSEACTIVITYLINEWSSERVICE_EXCEPTION!= null) {
            throw WAREHOUSEACTIVITYLINEWSSERVICE_EXCEPTION;
        }
        return WAREHOUSEACTIVITYLINEWSSERVICE_WSDL_LOCATION;
    }

}
