
package com.dynamics.webServices.Bin_WS;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Bin_WS_Port", targetNamespace = "urn:microsoft-dynamics-schemas/page/bin_ws")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BinWSPort {


    /**
     * 
     * @param code
     * @param locationCode
     * @return
     *     returns com.dynamics.webServices.Bin_WS.BinWS
     */
    @WebMethod(operationName = "Read", action = "urn:microsoft-dynamics-schemas/page/bin_ws:Read")
    @WebResult(name = "Bin_WS", targetNamespace = "urn:microsoft-dynamics-schemas/page/bin_ws")
    @RequestWrapper(localName = "Read", targetNamespace = "urn:microsoft-dynamics-schemas/page/bin_ws", className = "com.dynamics.webServices.Bin_WS.Read")
    @ResponseWrapper(localName = "Read_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/bin_ws", className = "com.dynamics.webServices.Bin_WS.ReadResult")
    public BinWS read(
        @WebParam(name = "Location_Code", targetNamespace = "urn:microsoft-dynamics-schemas/page/bin_ws")
        String locationCode,
        @WebParam(name = "Code", targetNamespace = "urn:microsoft-dynamics-schemas/page/bin_ws")
        String code);

    /**
     * 
     * @param recId
     * @return
     *     returns com.dynamics.webServices.Bin_WS.BinWS
     */
    @WebMethod(operationName = "ReadByRecId", action = "urn:microsoft-dynamics-schemas/page/bin_ws:ReadByRecId")
    @WebResult(name = "Bin_WS", targetNamespace = "urn:microsoft-dynamics-schemas/page/bin_ws")
    @RequestWrapper(localName = "ReadByRecId", targetNamespace = "urn:microsoft-dynamics-schemas/page/bin_ws", className = "com.dynamics.webServices.Bin_WS.ReadByRecId")
    @ResponseWrapper(localName = "ReadByRecId_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/bin_ws", className = "com.dynamics.webServices.Bin_WS.ReadByRecIdResult")
    public BinWS readByRecId(
        @WebParam(name = "recId", targetNamespace = "urn:microsoft-dynamics-schemas/page/bin_ws")
        String recId);

    /**
     * 
     * @param filter
     * @param setSize
     * @param bookmarkKey
     * @return
     *     returns com.dynamics.webServices.Bin_WS.BinWSList
     */
    @WebMethod(operationName = "ReadMultiple", action = "urn:microsoft-dynamics-schemas/page/bin_ws:ReadMultiple")
    @WebResult(name = "ReadMultiple_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/bin_ws")
    @RequestWrapper(localName = "ReadMultiple", targetNamespace = "urn:microsoft-dynamics-schemas/page/bin_ws", className = "com.dynamics.webServices.Bin_WS.ReadMultiple")
    @ResponseWrapper(localName = "ReadMultiple_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/bin_ws", className = "com.dynamics.webServices.Bin_WS.ReadMultipleResult")
    public BinWSList readMultiple(
        @WebParam(name = "filter", targetNamespace = "urn:microsoft-dynamics-schemas/page/bin_ws")
        List<BinWSFilter> filter,
        @WebParam(name = "bookmarkKey", targetNamespace = "urn:microsoft-dynamics-schemas/page/bin_ws")
        String bookmarkKey,
        @WebParam(name = "setSize", targetNamespace = "urn:microsoft-dynamics-schemas/page/bin_ws")
        int setSize);

    /**
     * 
     * @param key
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "IsUpdated", action = "urn:microsoft-dynamics-schemas/page/bin_ws:IsUpdated")
    @WebResult(name = "IsUpdated_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/bin_ws")
    @RequestWrapper(localName = "IsUpdated", targetNamespace = "urn:microsoft-dynamics-schemas/page/bin_ws", className = "com.dynamics.webServices.Bin_WS.IsUpdated")
    @ResponseWrapper(localName = "IsUpdated_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/bin_ws", className = "com.dynamics.webServices.Bin_WS.IsUpdatedResult")
    public boolean isUpdated(
        @WebParam(name = "Key", targetNamespace = "urn:microsoft-dynamics-schemas/page/bin_ws")
        String key);

    /**
     * 
     * @param key
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetRecIdFromKey", action = "urn:microsoft-dynamics-schemas/page/bin_ws:GetRecIdFromKey")
    @WebResult(name = "GetRecIdFromKey_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/bin_ws")
    @RequestWrapper(localName = "GetRecIdFromKey", targetNamespace = "urn:microsoft-dynamics-schemas/page/bin_ws", className = "com.dynamics.webServices.Bin_WS.GetRecIdFromKey")
    @ResponseWrapper(localName = "GetRecIdFromKey_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/bin_ws", className = "com.dynamics.webServices.Bin_WS.GetRecIdFromKeyResult")
    public String getRecIdFromKey(
        @WebParam(name = "Key", targetNamespace = "urn:microsoft-dynamics-schemas/page/bin_ws")
        String key);

    /**
     * 
     * @param binWS
     */
    @WebMethod(operationName = "Create", action = "urn:microsoft-dynamics-schemas/page/bin_ws:Create")
    @RequestWrapper(localName = "Create", targetNamespace = "urn:microsoft-dynamics-schemas/page/bin_ws", className = "com.dynamics.webServices.Bin_WS.Create")
    @ResponseWrapper(localName = "Create_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/bin_ws", className = "com.dynamics.webServices.Bin_WS.CreateResult")
    public void create(
        @WebParam(name = "Bin_WS", targetNamespace = "urn:microsoft-dynamics-schemas/page/bin_ws", mode = WebParam.Mode.INOUT)
        Holder<BinWS> binWS);

    /**
     * 
     * @param binWSList
     */
    @WebMethod(operationName = "CreateMultiple", action = "urn:microsoft-dynamics-schemas/page/bin_ws:CreateMultiple")
    @RequestWrapper(localName = "CreateMultiple", targetNamespace = "urn:microsoft-dynamics-schemas/page/bin_ws", className = "com.dynamics.webServices.Bin_WS.CreateMultiple")
    @ResponseWrapper(localName = "CreateMultiple_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/bin_ws", className = "com.dynamics.webServices.Bin_WS.CreateMultipleResult")
    public void createMultiple(
        @WebParam(name = "Bin_WS_List", targetNamespace = "urn:microsoft-dynamics-schemas/page/bin_ws", mode = WebParam.Mode.INOUT)
        Holder<BinWSList> binWSList);

    /**
     * 
     * @param binWS
     */
    @WebMethod(operationName = "Update", action = "urn:microsoft-dynamics-schemas/page/bin_ws:Update")
    @RequestWrapper(localName = "Update", targetNamespace = "urn:microsoft-dynamics-schemas/page/bin_ws", className = "com.dynamics.webServices.Bin_WS.Update")
    @ResponseWrapper(localName = "Update_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/bin_ws", className = "com.dynamics.webServices.Bin_WS.UpdateResult")
    public void update(
        @WebParam(name = "Bin_WS", targetNamespace = "urn:microsoft-dynamics-schemas/page/bin_ws", mode = WebParam.Mode.INOUT)
        Holder<BinWS> binWS);

    /**
     * 
     * @param binWSList
     */
    @WebMethod(operationName = "UpdateMultiple", action = "urn:microsoft-dynamics-schemas/page/bin_ws:UpdateMultiple")
    @RequestWrapper(localName = "UpdateMultiple", targetNamespace = "urn:microsoft-dynamics-schemas/page/bin_ws", className = "com.dynamics.webServices.Bin_WS.UpdateMultiple")
    @ResponseWrapper(localName = "UpdateMultiple_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/bin_ws", className = "com.dynamics.webServices.Bin_WS.UpdateMultipleResult")
    public void updateMultiple(
        @WebParam(name = "Bin_WS_List", targetNamespace = "urn:microsoft-dynamics-schemas/page/bin_ws", mode = WebParam.Mode.INOUT)
        Holder<BinWSList> binWSList);

    /**
     * 
     * @param key
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "Delete", action = "urn:microsoft-dynamics-schemas/page/bin_ws:Delete")
    @WebResult(name = "Delete_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/bin_ws")
    @RequestWrapper(localName = "Delete", targetNamespace = "urn:microsoft-dynamics-schemas/page/bin_ws", className = "com.dynamics.webServices.Bin_WS.Delete")
    @ResponseWrapper(localName = "Delete_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/bin_ws", className = "com.dynamics.webServices.Bin_WS.DeleteResult")
    public boolean delete(
        @WebParam(name = "Key", targetNamespace = "urn:microsoft-dynamics-schemas/page/bin_ws")
        String key);

}
