
package com.dynamics.webServices.Employee_Login;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Employee_Login", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/Employee_Login", wsdlLocation = "./wsdl//Employee_Login.xml")
public class EmployeeLogin_Service
    extends Service
{

    private final static URL EMPLOYEELOGIN_WSDL_LOCATION;
    private final static WebServiceException EMPLOYEELOGIN_EXCEPTION;
    private final static QName EMPLOYEELOGIN_QNAME = new QName("urn:microsoft-dynamics-schemas/codeunit/Employee_Login", "Employee_Login");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("./wsdl//Employee_Login.xml");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EMPLOYEELOGIN_WSDL_LOCATION = url;
        EMPLOYEELOGIN_EXCEPTION = e;
    }

    public EmployeeLogin_Service() {
        super(__getWsdlLocation(), EMPLOYEELOGIN_QNAME);
    }

    public EmployeeLogin_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), EMPLOYEELOGIN_QNAME, features);
    }

    public EmployeeLogin_Service(URL wsdlLocation) {
        super(wsdlLocation, EMPLOYEELOGIN_QNAME);
    }

    public EmployeeLogin_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EMPLOYEELOGIN_QNAME, features);
    }

    public EmployeeLogin_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmployeeLogin_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EmployeeLoginPort
     */
    @WebEndpoint(name = "Employee_Login_Port")
    public EmployeeLoginPort getEmployeeLoginPort() {
        return super.getPort(new QName("urn:microsoft-dynamics-schemas/codeunit/Employee_Login", "Employee_Login_Port"), EmployeeLoginPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmployeeLoginPort
     */
    @WebEndpoint(name = "Employee_Login_Port")
    public EmployeeLoginPort getEmployeeLoginPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:microsoft-dynamics-schemas/codeunit/Employee_Login", "Employee_Login_Port"), EmployeeLoginPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EMPLOYEELOGIN_EXCEPTION!= null) {
            throw EMPLOYEELOGIN_EXCEPTION;
        }
        return EMPLOYEELOGIN_WSDL_LOCATION;
    }

}
