
package com.dynamics.webServices.Production_Order_WS;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Production_Order_WS_Port", targetNamespace = "urn:microsoft-dynamics-schemas/page/production_order_ws")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductionOrderWSPort {


    /**
     * 
     * @param no
     * @param status
     * @return
     *     returns com.dynamics.webServices.Production_Order_WS.ProductionOrderWS
     */
    @WebMethod(operationName = "Read", action = "urn:microsoft-dynamics-schemas/page/production_order_ws:Read")
    @WebResult(name = "Production_Order_WS", targetNamespace = "urn:microsoft-dynamics-schemas/page/production_order_ws")
    @RequestWrapper(localName = "Read", targetNamespace = "urn:microsoft-dynamics-schemas/page/production_order_ws", className = "com.dynamics.webServices.Production_Order_WS.Read")
    @ResponseWrapper(localName = "Read_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/production_order_ws", className = "com.dynamics.webServices.Production_Order_WS.ReadResult")
    public ProductionOrderWS read(
        @WebParam(name = "Status", targetNamespace = "urn:microsoft-dynamics-schemas/page/production_order_ws")
        String status,
        @WebParam(name = "No", targetNamespace = "urn:microsoft-dynamics-schemas/page/production_order_ws")
        String no);

    /**
     * 
     * @param recId
     * @return
     *     returns com.dynamics.webServices.Production_Order_WS.ProductionOrderWS
     */
    @WebMethod(operationName = "ReadByRecId", action = "urn:microsoft-dynamics-schemas/page/production_order_ws:ReadByRecId")
    @WebResult(name = "Production_Order_WS", targetNamespace = "urn:microsoft-dynamics-schemas/page/production_order_ws")
    @RequestWrapper(localName = "ReadByRecId", targetNamespace = "urn:microsoft-dynamics-schemas/page/production_order_ws", className = "com.dynamics.webServices.Production_Order_WS.ReadByRecId")
    @ResponseWrapper(localName = "ReadByRecId_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/production_order_ws", className = "com.dynamics.webServices.Production_Order_WS.ReadByRecIdResult")
    public ProductionOrderWS readByRecId(
        @WebParam(name = "recId", targetNamespace = "urn:microsoft-dynamics-schemas/page/production_order_ws")
        String recId);

    /**
     * 
     * @param filter
     * @param setSize
     * @param bookmarkKey
     * @return
     *     returns com.dynamics.webServices.Production_Order_WS.ProductionOrderWSList
     */
    @WebMethod(operationName = "ReadMultiple", action = "urn:microsoft-dynamics-schemas/page/production_order_ws:ReadMultiple")
    @WebResult(name = "ReadMultiple_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/production_order_ws")
    @RequestWrapper(localName = "ReadMultiple", targetNamespace = "urn:microsoft-dynamics-schemas/page/production_order_ws", className = "com.dynamics.webServices.Production_Order_WS.ReadMultiple")
    @ResponseWrapper(localName = "ReadMultiple_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/production_order_ws", className = "com.dynamics.webServices.Production_Order_WS.ReadMultipleResult")
    public ProductionOrderWSList readMultiple(
        @WebParam(name = "filter", targetNamespace = "urn:microsoft-dynamics-schemas/page/production_order_ws")
        List<ProductionOrderWSFilter> filter,
        @WebParam(name = "bookmarkKey", targetNamespace = "urn:microsoft-dynamics-schemas/page/production_order_ws")
        String bookmarkKey,
        @WebParam(name = "setSize", targetNamespace = "urn:microsoft-dynamics-schemas/page/production_order_ws")
        int setSize);

    /**
     * 
     * @param key
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "IsUpdated", action = "urn:microsoft-dynamics-schemas/page/production_order_ws:IsUpdated")
    @WebResult(name = "IsUpdated_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/production_order_ws")
    @RequestWrapper(localName = "IsUpdated", targetNamespace = "urn:microsoft-dynamics-schemas/page/production_order_ws", className = "com.dynamics.webServices.Production_Order_WS.IsUpdated")
    @ResponseWrapper(localName = "IsUpdated_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/production_order_ws", className = "com.dynamics.webServices.Production_Order_WS.IsUpdatedResult")
    public boolean isUpdated(
        @WebParam(name = "Key", targetNamespace = "urn:microsoft-dynamics-schemas/page/production_order_ws")
        String key);

    /**
     * 
     * @param key
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetRecIdFromKey", action = "urn:microsoft-dynamics-schemas/page/production_order_ws:GetRecIdFromKey")
    @WebResult(name = "GetRecIdFromKey_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/production_order_ws")
    @RequestWrapper(localName = "GetRecIdFromKey", targetNamespace = "urn:microsoft-dynamics-schemas/page/production_order_ws", className = "com.dynamics.webServices.Production_Order_WS.GetRecIdFromKey")
    @ResponseWrapper(localName = "GetRecIdFromKey_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/production_order_ws", className = "com.dynamics.webServices.Production_Order_WS.GetRecIdFromKeyResult")
    public String getRecIdFromKey(
        @WebParam(name = "Key", targetNamespace = "urn:microsoft-dynamics-schemas/page/production_order_ws")
        String key);

}
